import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ocr_engine.frontend import frontend_html


class FrontendTests(unittest.TestCase):
    def test_frontend_html_matches_exported_public_index(self):
        exported_html = (ROOT / "public" / "index.html").read_text(encoding="utf-8")

        self.assertEqual(frontend_html(), exported_html)

    def test_frontend_html_matches_vehicle_angle_style_autoprocess_workflow(self):
        html = frontend_html()

        self.assertIn('id="ocr-form"', html)
        self.assertIn('id="file-input"', html)
        self.assertIn("Choose a photo", html)
        self.assertIn('class="upload-card"', html)
        self.assertIn('class="checkerboard"', html)
        self.assertIn("html {\n      min-height: 100%;\n      overflow-y: auto;", html)
        self.assertIn("overflow-x: hidden;", html)
        self.assertIn("overflow-y: auto;", html)
        self.assertIn('class="document-tabs"', html)
        self.assertIn('data-document-type="KTP"', html)
        self.assertIn('data-document-type="STNK"', html)
        self.assertIn('let selectedDocumentType = "KTP";', html)
        self.assertIn("handleDocumentTabClick", html)
        self.assertIn("renderDocumentTabs", html)
        self.assertIn("ocrEndpoint()", html)
        self.assertIn("document_type=${encodeURIComponent(selectedDocumentType)}", html)
        self.assertIn('fileInput.addEventListener("change", handleFileSelection);', html)
        self.assertIn('documentTabs.forEach((tab) => tab.addEventListener("click", handleDocumentTabClick));', html)
        self.assertIn("runOcr(file)", html)
        self.assertIn('id="result-preview-img"', html)
        self.assertIn('id="fields-body"', html)
        self.assertIn('id="raw-json"', html)
        self.assertIn('id="copy-json"', html)
        self.assertIn("FIELD_ORDER", html)
        self.assertIn("orderedFieldEntries", html)
        self.assertIn("renderResult(data, roundtripMs)", html)
        self.assertIn('id="summary-status"', html)
        self.assertIn('id="summary-processing-time"', html)
        self.assertIn("Waktu proses", html)
        self.assertIn("Lolos", html)
        self.assertIn("Perlu review", html)
        self.assertIn("field-row", html)
        self.assertIn("field-value", html)
        self.assertIn("FIELD_LABELS", html)
        self.assertIn("server mengembalikan non-JSON", html)

        self.assertNotIn('id="dropzone"', html)
        self.assertNotIn('name="document_type"', html)
        self.assertNotIn('id="document-type"', html)
        self.assertNotIn("Tipe dokumen", html)
        self.assertNotIn('name="engine_type"', html)
        self.assertNotIn('id="engine-type"', html)
        self.assertNotIn("Engine", html)
        self.assertNotIn('name="vps_api_key"', html)
        self.assertNotIn('id="vps-api-key"', html)
        self.assertNotIn("VPS API Key", html)
        self.assertNotIn("Isi kalau memilih engine VPS", html)
        self.assertNotIn('id="submit-button"', html)
        self.assertNotIn("Jalankan OCR", html)
        self.assertNotIn('id="reset-button"', html)
        self.assertNotIn(">Reset<", html)
        self.assertNotIn("Pilih gambar untuk mulai.", html)
        self.assertNotIn('form.addEventListener("submit"', html)
        self.assertNotIn("configureEngineOptions", html)
        self.assertNotIn("isLocalRuntime", html)
        self.assertNotIn('"/ocr?document_type=AUTO', html)
        self.assertNotIn("document_type=AUTO", html)
        self.assertNotIn("/ocr/vps", html)
        self.assertNotIn("ai-comparison-section", html)
        self.assertNotIn("comparisonEndpointFor", html)
        self.assertNotIn("renderAiComparison", html)
        self.assertNotIn("OpenClaw", html)
        self.assertNotIn("enrichment-section", html)
        self.assertNotIn("/ocr/enrichment/", html)
        self.assertNotIn("renderEnrichment", html)
        self.assertNotIn("Output IT", html)
        self.assertNotIn("renderItOutput", html)
        self.assertNotIn("Raw OCR Masked", html)
        self.assertNotIn("summary-pipeline-time", html)
        self.assertNotIn("summary-prepare-time", html)
        self.assertNotIn("summary-quality-time", html)
        self.assertNotIn("summary-resolution", html)
        self.assertNotIn("summary-retry", html)
        self.assertNotIn("summary-auto-publish", html)
        self.assertNotIn("summary-warnings", html)
        self.assertNotIn("summary-engine-used", html)
        self.assertNotIn("summary-ocr-time", html)
        self.assertNotIn("summary-roundtrip-time", html)
        self.assertNotIn("summary-tokens", html)
        self.assertNotIn(">Provider<", html)
        self.assertNotIn(">Roundtrip<", html)
        self.assertNotIn(">OCR tokens<", html)
        self.assertNotIn(">OCR time<", html)
        self.assertNotIn(">Decision<", html)
        self.assertNotIn("approved_for_auto</strong>", html)
        self.assertNotIn("<table>", html)
        self.assertNotIn("<th>Field</th>", html)
        self.assertNotIn("<th>Status</th>", html)
        self.assertNotIn("<th>Confidence</th>", html)
        self.assertNotIn("field-status", html)
        self.assertNotIn("quality gate", html.lower())

    def test_frontend_html_preserves_review_states(self):
        html = frontend_html()

        self.assertIn("needs_review", html)
        self.assertIn("approved_for_auto", html)
        self.assertIn("rejected_input", html)
        self.assertIn("Reasons:", html)
        self.assertIn("Warnings:", html)


if __name__ == "__main__":
    unittest.main()
