import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ocr_engine.frontend import frontend_html


class FrontendTests(unittest.TestCase):
    def test_frontend_html_contains_upload_workflow(self):
        html = frontend_html()

        self.assertIn('id="ocr-form"', html)
        self.assertIn('name="document_type"', html)
        self.assertIn('<option value="KTP" selected>KTP</option>', html)
        self.assertIn('/ocr?document_type=${encodeURIComponent(documentType)}&mode=fast', html)
        self.assertIn('/ocr/vps?document_type=${encodeURIComponent(documentType)}&mode=fast', html)
        self.assertIn('name="engine_type"', html)
        self.assertIn('value="local"', html)
        self.assertIn("configureEngineOptions", html)
        self.assertIn("isLocalRuntime", html)
        self.assertIn('localOption.remove()', html)
        self.assertIn('engineSelect.value = "vps-local"', html)
        self.assertIn('name="vps_api_key"', html)
        self.assertIn('name="compare_openclaw"', html)
        self.assertIn('id="compare-openclaw"', html)
        self.assertIn("Bandingkan dengan VPS OpenClaw AI", html)
        self.assertIn('name="quality_gate"', html)
        self.assertIn('id="quality-gate"', html)
        self.assertIn("Cek kualitas sebelum OCR", html)
        self.assertNotIn('name="purchase_mode"', html)
        self.assertNotIn('id="purchase-mode"', html)
        self.assertNotIn("Mode pembelian:", html)
        self.assertNotIn('id="endpoint-ocr-tab"', html)
        self.assertNotIn('id="full-ocr-tab"', html)
        self.assertNotIn("Endpoint OCR", html)
        self.assertNotIn("Full OCR", html)
        self.assertNotIn("/ocr/purchase/ktp", html)
        self.assertIn("/ocr/ktp?mode=fast", html)
        self.assertNotIn("runManualFullOcr", html)
        self.assertNotIn("Klik tab Full OCR untuk menjalankan OCR lengkap", html)
        self.assertIn("/ocr/purchase/stnk", html)
        self.assertIn("background_full_ocr", html)
        self.assertNotIn('name="processing_mode"', html)
        self.assertNotIn('id="processing-mode"', html)
        self.assertNotIn("Fast checkout", html)
        self.assertNotIn(">Accurate<", html)
        self.assertNotIn('value="agent"', html)
        self.assertNotIn('value="vps-agent"', html)
        self.assertNotIn("Agent OpenClaw/Codex", html)
        self.assertNotIn("VPS Agent OpenClaw/Codex", html)
        self.assertIn('name="file"', html)
        self.assertIn("/ocr/ktp", html)
        self.assertIn("/ocr/stnk", html)
        self.assertIn("/ocr?document_type=", html)
        self.assertIn("/ocr/vps/ktp", html)
        self.assertIn("/ocr/vps/ktp?mode=fast", html)
        self.assertIn("/ocr/vps/stnk", html)
        self.assertIn("/ocr/vps/agent/ktp", html)
        self.assertIn("/ocr/vps/agent/stnk", html)
        self.assertIn("comparisonEndpointFor", html)
        self.assertIn("ai-comparison-section", html)
        self.assertIn("ai-comparison-fields-body", html)
        self.assertIn("comparison-table", html)
        self.assertIn("PaddleOCR", html)
        self.assertIn("Cocok", html)
        self.assertIn("Catatan", html)
        self.assertIn("buildFieldComparisonRows", html)
        self.assertIn("fieldValuesMatch", html)
        self.assertIn("Sama setelah normalisasi", html)
        self.assertIn("parseJsonResponse", html)
        self.assertIn("server mengembalikan non-JSON", html)
        self.assertIn("runClientQualityGate", html)
        self.assertNotIn("/ocr/stnk?mode=", html)
        self.assertNotIn("/ocr/vps/stnk?mode=", html)
        self.assertIn("X-VPS-API-Key", html)
        self.assertIn("Cara Integrasi API", html)
        self.assertIn("VPS/VPN OCR", html)
        self.assertIn("jaringan/VPN", html)
        self.assertNotIn("Contoh Vercel API Route Proxy", html)
        self.assertNotIn("Contoh JavaScript dari Frontend", html)
        self.assertNotIn("Response Decision", html)
        self.assertNotIn("KTP pembanding OpenClaw", html)
        self.assertNotIn("STNK pembanding OpenClaw", html)
        self.assertNotIn("Jangan taruh API key langsung di frontend publik", html)
        self.assertIn("needs_review", html)
        self.assertIn("input_assessment", html)
        self.assertIn("summary-decision", html)
        self.assertIn("summary-engine-used", html)
        self.assertIn("summary-retry", html)
        self.assertIn("summary-resolution", html)
        self.assertIn("summary-pipeline-time", html)
        self.assertIn("summary-ocr-time", html)
        self.assertNotIn("ti-compatible-section", html)
        self.assertNotIn("TI Compatible Output", html)
        self.assertNotIn("renderTiCompatible", html)
        self.assertIn("Output IT", html)
        self.assertIn("it-output-json", html)
        self.assertIn("renderItOutput", html)
        self.assertIn("initial-section", html)
        self.assertIn("enrichment-section", html)
        self.assertIn("enrichment-status", html)
        self.assertIn("/ocr/enrichment/", html)
        self.assertNotIn("attempt < 90", html)

    def test_frontend_explains_stnk_fast_timeout_as_pending_enrichment(self):
        html = frontend_html()

        self.assertIn("isProcessingTimeout", html)
        self.assertIn("OCR masih berjalan", html)
        self.assertIn("Hasil awal belum berisi field OCR", html)


if __name__ == "__main__":
    unittest.main()
